---
title: "p8105_hw5_jy2965"
author: "Jun Yin"
date: "11/8/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(plyr)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))

```



## Problem 1


```{r}
set.seed(10)
iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))
```


```{r}
#build the function
replace_na_fun = function(vec) {
  
  if (is.numeric(vec)) {
    vec[is.na(vec)] = mean(vec, na.rm = TRUE)
  } else if (is.character(vec)) {
    vec[is.na(vec)] = "virginica"
  } 
  
 vec
}
#using the function with for loop
iris_noneed = vector("list", length = 5)
for (i in 1:5) {
  
  iris_noneed[[i]] = replace_na_fun(iris_with_missing[[i]])
  
}
 
# Apply this function to the columns of iris_with_missing using a map statement
iris_without_missing = map_df(iris_with_missing,replace_na_fun) 

```


I replaeced missiong value based on the instruction and generated a new dataset named iris_withou_missing.



## Problem 2





